
import { Card, CardHeader, CardTitle, CardContent, CardDescription, CardFooter } from '@/components/ui/card';
import { Button } from '@/components/ui/button';
import { useStore } from '@/lib/store';
import { Video, Sparkles, Zap, Bot } from 'lucide-react';
import { cn } from '@/lib/utils'; // Assuming this exists, or I will use standard class
// If cn doesn't exist, I'll just use string templates. Let's check imports in other files.
// page.tsx uses standard classes. I will verify if 'cn' is available or just avoid it.
// Checking `globals.css` existence suggests standard shadcn usage, which usually has `lib/utils.ts`.

export function SelectionStep() {
    const { setStep, setVideoMode } = useStore();

    const handleSelect = (mode: 'remotion' | 'ai') => {
        setVideoMode(mode);
        setStep('video');
    };

    return (
        <div className="w-full max-w-5xl mx-auto space-y-8 animate-in fade-in slide-in-from-bottom-4">
            <div className="text-center space-y-2">
                <h2 className="text-3xl font-bold bg-gradient-to-r from-primary to-purple-600 bg-clip-text text-transparent">
                    Choose Your Production Style
                </h2>
                <p className="text-muted-foreground">Select how you want your final video to be generated.</p>
            </div>

            <div className="grid grid-cols-1 md:grid-cols-2 gap-6">
                {/* Standard Option */}
                <Card
                    className="relative group cursor-pointer hover:border-primary/50 transition-all duration-300 border-primary/10 bg-card/50 backdrop-blur-xl overflow-hidden hover:shadow-2xl hover:shadow-primary/10"
                    onClick={() => handleSelect('remotion')}
                >
                    <div className="absolute inset-0 bg-gradient-to-br from-primary/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
                    <CardHeader>
                        <div className="w-12 h-12 rounded-xl bg-primary/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                            <Zap className="w-6 h-6 text-primary" />
                        </div>
                        <CardTitle className="text-2xl">Standard Video</CardTitle>
                        <CardDescription className="text-base">Quick & Efficient Template</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        <ul className="space-y-2 text-sm text-muted-foreground">
                            <li className="flex items-center gap-2">
                                <span className="w-1.5 h-1.5 rounded-full bg-primary" />
                                Proven High-Converting Template
                            </li>
                            <li className="flex items-center gap-2">
                                <span className="w-1.5 h-1.5 rounded-full bg-primary" />
                                Instant Rendering with Remotion
                            </li>
                            <li className="flex items-center gap-2">
                                <span className="w-1.5 h-1.5 rounded-full bg-primary" />
                                Perfect for Social Media Ads
                            </li>
                        </ul>
                    </CardContent>
                    <CardFooter>
                        <Button className="w-full" variant="secondary">Select Standard</Button>
                    </CardFooter>
                </Card>

                {/* AI Advanced Option */}
                <Card
                    className="relative group cursor-pointer hover:border-purple-500/50 transition-all duration-300 border-purple-500/10 bg-card/50 backdrop-blur-xl overflow-hidden hover:shadow-2xl hover:shadow-purple-500/10"
                    onClick={() => handleSelect('ai')}
                >
                    <div className="absolute inset-0 bg-gradient-to-br from-purple-500/5 to-transparent opacity-0 group-hover:opacity-100 transition-opacity" />
                    <div className="absolute top-0 right-0 px-3 py-1 bg-purple-500/20 text-purple-500 text-xs font-bold rounded-bl-xl border-b border-l border-purple-500/20">
                        RECOMMENDED
                    </div>
                    <CardHeader>
                        <div className="w-12 h-12 rounded-xl bg-purple-500/10 flex items-center justify-center mb-4 group-hover:scale-110 transition-transform">
                            <Sparkles className="w-6 h-6 text-purple-500" />
                        </div>
                        <CardTitle className="text-2xl">AI Advanced Video</CardTitle>
                        <CardDescription className="text-base">Fully Generated by Gemini</CardDescription>
                    </CardHeader>
                    <CardContent className="space-y-4">
                        <ul className="space-y-2 text-sm text-muted-foreground">
                            <li className="flex items-center gap-2">
                                <span className="w-1.5 h-1.5 rounded-full bg-purple-500" />
                                Advanced Scene Composition
                            </li>
                            <li className="flex items-center gap-2">
                                <span className="w-1.5 h-1.5 rounded-full bg-purple-500" />
                                Dynamic Text & Effects
                            </li>
                            <li className="flex items-center gap-2">
                                <span className="w-1.5 h-1.5 rounded-full bg-purple-500" />
                                Optimized for Storytelling
                            </li>
                        </ul>
                    </CardContent>
                    <CardFooter>
                        <Button className="w-full bg-purple-600 hover:bg-purple-700 text-white">Select Advanced AI</Button>
                    </CardFooter>
                </Card>
            </div>
        </div>
    );
}
